### ISSUE TITLE
Make SpeckleView Dockable in Revit.

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleRevit#11]
First draft is just a floating form. I've not even handled the logic for it to stay on top of Revit.

**Comment by radumg** [comment]
FYI, this one is not as straightforward as it might seem at first, `DockableWindow` has its own API in Revit.

Reading list
- http://thebuildingcoder.typepad.com/blog/2013/05/a-simpler-dockable-panel-sample.html
- http://spiderinnet.typepad.com/blog/2014/10/revit-net-api-create-custom-dockable-pane-dockablepane-pt-1.html

**Comment by archinate** [comment]
@fraguada I merged in some boilerplate code for setting up dockable windows in the Revit project. PR https://github.com/speckleworks/SpeckleRevit/pull/14.

The dockable window is registered at application startup with additional command data being accessed when the Ribbon command is run. There is also a special workflow for safely running transactions on a Revit document from a modeless dialog. This is shown the form_MainDock and ExtCmdModeless classes.

I have only ever done dockable forms with WPF forms in Revit so it appears there may be a need to switch from CefSharp.Winforms to CefSharp.Wpf (I am not familiar with CefSharp and its uses)
